# Replace YOUR_ORG and YOUR_PROJECT_KEY with values from SonarCloud project setup.
sonar.organization=it22113740
sonar.projectKey=it22113740_ctse_test
sonar.projectName=ctse_test
#source code directories
sonar.sources=services,frontend
#exclude files
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.config.js,**/*.config.ts,**/coverage/**
#sonar.java.binaries=target/classes
